### ISSUE TITLE
Curriculum

### ISSUE THREAD

**Issue by kuteken-miki-mulodo** [phan-tai-mulodo/training#1]
When you "Done" it, please check the box.

- [ ] Git as Team work  #2 
- [ ] English tech news #3
- [ ] Read book "Soft skill" #4
- [ ] Present at TGIF #5
- [ ] AWS video training #6

**Comment by kuteken-miki-mulodo** [comment]
Github released new feature on Github today.
https://github.com/blog/2256-a-whole-new-github-universe-announcing-new-tools-forums-and-features

We'll use Project feature to manage this course. So I'll close this issue.
https://github.com/phan-tai-mulodo/training/projects/1
