### ISSUE TITLE
Git as Team work

### ISSUE THREAD

**Issue by kuteken-miki-mulodo** [phan-tai-mulodo/training#2]
## Purpose

- Git and Github is really important tool for team work.

## Goal

Be checked by trainer

- [x] Understand Git structure
- [x] Fluently Git command
- [x] Fluently Pull request

## Documents

- Git as Team work
  - https://docs.google.com/presentation/d/1a7Gr06Pqc8glAqiP_JD0cO0Pe8SrvWPFjrlLO5o41jc/edit#slide=id.p

## Tasks

- [x] Kick off MTG
- [x] Reading document
- [x] Estimation
- [x] Try the steps
- [x] Write report document
- [x] Wrap up MTG
- [x] Write wiki

**Comment by phan-tai-mulodo** [comment]
I writed wiki for this task, please check follow link below
https://github.com/phan-tai-mulodo/training/wiki/Git-Memo

**Comment by kuteken-miki-mulodo** [comment]
@phan-tai-mulodo 

> c37ace7 is commit have been cost from the action `git reset --hard HEAD~` at 4839ce5 commit. So now will restore the status quo of c37ace7 commit.

Nice wiki for memo 👍  I wanna point one thing. This sentence meaning is unclear as English. IMO it's should be

> c37ace7 is lost commit by `git reset --hard HEAD~` command at 4839ce5 commit.
> We can restore a previous state committed as c37ace7 by below command.

----

You've already moved the card to "Done" on Project board. After fix it, close this issue. Thanks!

**Comment by phan-tai-mulodo** [comment]
Thank you, i fixed it
