### ISSUE TITLE
AWS video training

### ISSUE THREAD

**Issue by kuteken-miki-mulodo** [phan-tai-mulodo/training#6]
## Purpose

- We're using AWS on many Project. We should know about AWS.

## Goal

- [x] Understand about AWS overview

## Documents

- APN
  - https://www.apn-portal.com/
- AWS Technical Professional (Released September 2015)
  - You can find it at “Classes > APN Partner Accreditations”

## Tasks

At first, plz add your tasks here!

**Comment by phan-tai-mulodo** [comment]
### Tasks for AWS Technical Professional Modules
- [ ] Introduction to Amazon Web Services
- [ ] AWS Core Services 
   - [ ] Amazon EC2
   - [ ] Elastic Load Balancing
   - [ ] Auto Scaling
   - [ ] AWS Lambda
   - [ ] Amazon RDS
   - [ ] Amazon DynamoDB
   - [ ] AWS DMS
   - [ ] Amazon VPC
   - [ ] Amazon Route 53
   - [ ] Amazon S3
   - [ ] Amazon EBS
   - [ ] Amazon Glacier
   - [ ] AWS IAM
   - [ ] Amazon CloudWatch
   - [ ] Amazon Inspector
   - [ ] AWS WAF
   - [ ] AmazON RedShift
   - [ ] AWS CloudFormation
- [ ] AWS Cloud Solutions (Part 1)
- [ ] AWS Cloud Solutions (Part 2)
- [ ] AWS Security and Compliance

**Comment by phan-tai-mulodo** [comment]
AWS Technical Professional Modules Completed
![AWS Technical Professional Modules Completed](https://phan-tai-mulodo.github.io/training/assets/AWS-Technical-Professional-Modules.png)

AWS Technical Professional Certificate
![AWS Technical Professional Assessment](https://phan-tai-mulodo.github.io/training/assets/AWS-Technical-Professional-Certificate.png)

I completed 'AWS Technical Professional' with results score 25/24 points(passing score)
I wrote some summary content for lessons, please access link below
https://github.com/phan-tai-mulodo/training/wiki/AWS-Technical-Professional---Memo

**Comment by kuteken-miki-mulodo** [comment]
Congrats! 🎊  How was it? :)

If you want to try some services, I can make your IAM user on company's AWS account for try it on your hands. Please tell me the service name if you have. Let's discuss it tomorrow 👍 

----

Please close this issue, and move to Done on the board.

**Comment by phan-tai-mulodo** [comment]
Yes, I just know for knowledge the AWS.
So in the case of fact project, how to manage it then I'm unclear.
